<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Opencart\Admin\Controller\Marketplace;
require_once(__DIR__ . '/installer.0.kamod.php');
class Installer extends \extension\ka_extensions\marketplace\ControllerMarketplaceInstaller {
}