<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Opencart\Catalog\Model\Design;
require_once(__DIR__ . '/translation.0.kamod.php');
class Translation extends \extension\ka_extensions\design\ModelTranslation {
}