<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Opencart\Admin\Model\User;
require_once(__DIR__ . '/usergroup.0.kamod.php');
class UserGroup extends \extension\ka_extensions\user\ModelUserGrouop {
}