<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Opencart\System\Engine;
require_once(__DIR__ . '/loader.0.kamod.php');
class Loader extends \extension\ka_extensions\engine\Loader {
}