<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Opencart\Admin\Controller\User;
require_once(__DIR__ . '/userpermission.0.kamod.php');
class UserPermission extends \extension\ka_extensions\user\ControllerUserPermission {
}