<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Opencart\Admin\Controller\Startup;
require_once(__DIR__ . '/permission.0.kamod.php');
class Permission extends \extension\ka_extensions\startup\Permission {
}