<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Opencart\Admin\Model\Design;
require_once(__DIR__ . '/theme.0.kamod.php');
class Theme extends \extension\ka_extensions\ModelDesignTheme {
}