<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Opencart\Admin\Controller\Common;
require_once(__DIR__ . '/columnleft.0.kamod.php');
class ColumnLeft extends \extension\ka_product_import\ControllerCommonColumnLeft {
}