<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Opencart\Admin\Controller\Common;
require_once(__DIR__ . '/header.0.kamod.php');
class Header extends \extension\ka_extensions\common\Header {
}